# Generated by Django 5.1.6 on 2025-06-11 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('age_in_months', models.PositiveIntegerField(help_text='Use the lower bound in months for sorting')),
            ],
            options={
                'ordering': ['age_in_months'],
            },
        ),
        migrations.CreateModel(
            name='AgeMilestoneInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(choices=[('sit', 'Sitting'), ('crawl', 'Crawling'), ('stand', 'Standing'), ('walk', 'Walking'), ('run', 'Running'), ('jump', 'Jumping')], max_length=10)),
                ('description', models.TextField(help_text='Description of typical milestone achievement at this age')),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='myapp.agegroup')),
            ],
        ),
    ]
