# Generated by Django 5.1.6 on 2025-06-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_agemilestoneinfo_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='agemilestoneinfo',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image representing the milestone', null=True, upload_to='milestone_images/'),
        ),
    ]
