# Generated by Django 5.1.6 on 2025-06-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_agemilestoneinfo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agemilestoneinfo',
            name='age_group',
        ),
        migrations.DeleteModel(
            name='AgeGroup',
        ),
    ]
