# Generated by Django 5.1.6 on 2025-06-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_agemilestoneinfo_age_group_delete_agegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agemilestoneinfo',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image representing the milestone', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='agemilestoneinfo',
            name='milestone',
            field=models.CharField(choices=[('sit', 'Sitting without support'), ('stand', 'Standing with assistance'), ('crawl', 'Hands and knees crawling'), ('walk', 'Walking with assisstance'), ('standalone', 'Standing without support'), ('walkalone', 'Walking without support')], max_length=10),
        ),
    ]
