# Generated by Django 5.1.6 on 2025-06-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_agemilestoneinfo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agemilestoneinfo',
            name='milestone',
            field=models.CharField(choices=[('Sitting without support', 'Sitting without support'), ('Standing with assistance', 'Standing with assistance'), ('Hands and knees crawling', 'Hands and knees crawling'), ('Walking with assistance', 'Walking with assisstance'), ('Standing without support', 'Standing without support'), ('Walking without support', 'Walking without support')], max_length=40),
        ),
    ]
