# Generated by Django 5.1.6 on 2025-06-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_agemilestoneinfo_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agemilestoneinfo',
            name='milestone',
            field=models.CharField(choices=[('sit', 'Sitting without support'), ('stand', 'Standing with assistance'), ('crawl', 'Hands and knees crawling'), ('walk', 'Walking with assisstance'), ('standalone', 'Standing without support'), ('walkalone', 'Walking without support')], max_length=10),
        ),
    ]
