# Generated by Django 5.1.6 on 2025-06-22 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_agemilestoneinfo_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('age_range', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='milestones/')),
                ('milestone_display', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MilestonePercentile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentile', models.IntegerField()),
                ('age_months', models.FloatField()),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percentiles', to='myapp.milestone')),
            ],
            options={
                'ordering': ['percentile'],
                'unique_together': {('milestone', 'percentile')},
            },
        ),
        migrations.DeleteModel(
            name='AgeMilestoneInfo',
        ),
    ]
